@startuml

class Persona {
    -nombre                     : String
    -apellido                   : String
    -direccion                  : Direccion
    -fechaDeNacimiento          : localDate
    -sexo                       : Sexo
    -cuidadoresDisponibles      : CuidadoresDisponibles
    -puedeRecibirNotificaciones : Disponibilidad
    -reaccionFrenteIncidente    : FormasDeReaccion
    -rol                        : Rol
--
    +cambiarRol(rol)
    +cambiarReaccion(reaccion)
    +
}

class Transeunte {
    +viajar(Direccion posicionActual, Direccion destino, List<Cuidador> cuidadores)
    +comenzar(Direccion posicionActual, Direccion destino)
    +finalizar()
}

class CuidadoresDisponibles {
    -ciudadoresDisponibles : List<Persona>
}

class Direccion {
    -calle        : String
    -altura       : int
    -piso         : int
    -codigoPostal : Integer
}

enum Sexo {
    MASCULINO
    FEMENINO
    NOBINARIO
}

class Disponibilidad {
    -estaViajando : boolean
}

interface FormasDeReaccion {
    +reaccionar(Persona)
}

class AlertarACuidadores {
    +reaccionar(Persona)
}

class AlertarAPolicia {
    +reaccionar(Persona)
}

class LlamarAUsuario {
    +reaccionar(Persona)
}

class FalsaAlarma {
    +reaccionar(Persona)
}

class Notificador{
 -tipoDeNotificacion: TipoDeNotificacion
 +notificarCuidadores(Persona transeunte, Direccion destinoInicial, Direccion destinoFinal): void
}

interface TipoDeNotificacion{
 +notificarCuidadores(Persona transeunte, Direccion destinoInicial, Direccion destinoFinal): void
}

class NotificarSolicitudDeCuidado{
 +notificarCuidadores(Persona transeunte, Direccion destinoInicial, Direccion destinoFinal): void
}

class NotificarComienzoDeCuidado{
 +notificarCuidadores(Persona transeunte, Direccion destinoInicial, Direccion destinoFinal): void
}

class NotificarFinDeCuidado{
 +notificarCuidadores(Persona transeunte, Direccion destinoInicial, Direccion destinoFinal): void
}


Persona o-- Disponibilidad
Persona --> Direccion
Persona --> Sexo

CuidadoresDisponibles -->"*"Persona

Persona --> FormasDeReaccion
AlertarACuidadores ..|> FormasDeReaccion
AlertarAPolicia ..|> FormasDeReaccion
LlamarAUsuario ..|> FormasDeReaccion
FalsaAlarma ..|> FormasDeReaccion

NotificarComienzoDeCuidado ..|> TipoDeNotificacion
NotificarFinDeCuidado ..|> TipoDeNotificacion
NotificarSolicitudDeCuidado ..|> TipoDeNotificacion


@enduml